In [1]:
import time
from models.data_loader import load_dataset
import pandas as pd

## room occupancy

In [2]:
data = pd.read_csv("./data/Occupancy_Estimation.csv")
data['Room_Occupancy_Count'].value_counts()

Room_Occupancy_Count
0    8228
2     748
3     694
1     459
Name: count, dtype: int64

In [3]:
data['label'] = data['Room_Occupancy_Count'].apply(lambda x: 1 if x > 0 else -1)
data.head()

,Date,Time,S1_Temp,S2_Temp,S3_Temp,S4_Temp,S1_Light,S2_Light,S3_Light,S4_Light,S1_Sound,S2_Sound,S3_Sound,S4_Sound,S5_CO2,S5_CO2_Slope,S6_PIR,S7_PIR,Room_Occupancy_Count,label
0,2017/12/22,10:49:41,24.94,24.75,24.56,25.38,121,34,53,40,0.08,0.19,0.06,0.06,390,0.769231,0,0,1,1
1,2017/12/22,10:50:12,24.94,24.75,24.56,25.44,121,33,53,40,0.93,0.05,0.06,0.06,390,0.646154,0,0,1,1
2,2017/12/22,10:50:42,25.00,24.75,24.50,25.44,121,34,53,40,0.43,0.11,0.08,0.06,390,0.519231,0,0,1,1
3,2017/12/22,10:51:13,25.00,24.75,24.56,25.44,121,34,53,40,0.41,0.10,0.10,0.09,390,0.388462,0,0,1,1
4,2017/12/22,10:51:44,25.00,24.75,24.56,25.44,121,34,54,40,0.18,0.06,0.06,0.06,390,0.253846,0,0,1,1

In [4]:
data = data.drop(columns=['Room_Occupancy_Count', 'Date', 'Time'])
X = data.drop(columns=['label'])
y = data['label']
X.head()

,S1_Temp,S2_Temp,S3_Temp,S4_Temp,S1_Light,S2_Light,S3_Light,S4_Light,S1_Sound,S2_Sound,S3_Sound,S4_Sound,S5_CO2,S5_CO2_Slope,S6_PIR,S7_PIR
0,24.94,24.75,24.56,25.38,121,34,53,40,0.08,0.19,0.06,0.06,390,0.769231,0,0
1,24.94,24.75,24.56,25.44,121,33,53,40,0.93,0.05,0.06,0.06,390,0.646154,0,0
2,25.00,24.75,24.50,25.44,121,34,53,40,0.43,0.11,0.08,0.06,390,0.519231,0,0
3,25.00,24.75,24.56,25.44,121,34,53,40,0.41,0.10,0.10,0.09,390,0.388462,0,0
4,25.00,24.75,24.56,25.44,121,34,54,40,0.18,0.06,0.06,0.06,390,0.253846,0,0

In [6]:
import os
os.makedirs("./data/room-occupancy", exist_ok=True)
X.to_csv("./data/room-occupancy/X.csv", index=False)
y.to_csv("./data/room-occupancy/y.csv", index=False)

## heart failure

In [8]:
data = pd.read_csv("./data/heart_failure_clinical_records_dataset.csv")
data.value_counts()

age   anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  smoking  time  DEATH_EVENT
75.0  0        582                       0         20                 1                    265000.00  1.9               130           1    0        4     1              1
55.0  0        7861                      0         38                 0                    263358.03  1.1               136           1    0        6     1              1
65.0  0        146                       0         20                 0                    162000.00  1.3               129           1    1        7     1              1
50.0  1        111                       0         20                 0                    210000.00  1.9               137           1    0        7     1              1
65.0  1        160                       1         20                 0                    327000.00  2.7               116           0    0        8     1              1
                                                                                                                                                                        ..
62.0  0        61                        1         38                 1                    155000.00  1.1               143           1    1        270   0              1
55.0  0        1820                      0         38                 0                    270000.00  1.2               139           0    0        271   0              1
45.0  0        2060                      1         60                 0                    742000.00  0.8               138           0    0        278   0              1
               2413                      0         38                 0                    140000.00  1.4               140           1    1        280   0              1
50.0  0        196                       0         45                 0                    395000.00  1.6               136           1    1        285   0              1
Name: count, Length: 299, dtype: int64

In [9]:
data.columns.tolist()

['age',
 'anaemia',
 'creatinine_phosphokinase',
 'diabetes',
 'ejection_fraction',
 'high_blood_pressure',
 'platelets',
 'serum_creatinine',
 'serum_sodium',
 'sex',
 'smoking',
 'time',
 'DEATH_EVENT']

In [10]:
data.dtypes

age                         float64
anaemia                       int64
creatinine_phosphokinase      int64
diabetes                      int64
ejection_fraction             int64
high_blood_pressure           int64
platelets                   float64
serum_creatinine            float64
serum_sodium                  int64
sex                           int64
smoking                       int64
time                          int64
DEATH_EVENT                   int64
dtype: object

In [11]:
data['DEATH_EVENT'].value_counts()

DEATH_EVENT
0    203
1     96
Name: count, dtype: int64

In [12]:
data['time'].value_counts()

time
187    7
250    7
10     6
107    6
186    6
      ..
257    1
271    1
278    1
280    1
285    1
Name: count, Length: 148, dtype: int64

In [19]:
X = data.drop(columns=['DEATH_EVENT'])
y = data['DEATH_EVENT'].map({0: -1, 1: 1}).astype(int)

In [20]:
import os
os.makedirs("./data/heart-failure", exist_ok=True)
X.to_csv("./data/heart-failure/X.csv", index=False)
y.to_csv("./data/heart-failure/y.csv", index=False)

## breast cancer

In [22]:
import pandas as pd
import os

bc_path = "./data/wdbc.data"
bc_df = pd.read_csv(bc_path, header=None)

base_feats = [
    "radius", "texture", "perimeter", "area", "smoothness",
    "compactness", "concavity", "concave_points", "symmetry", "fractal_dimension"
]
feature_names = (
    [f"mean_{f}" for f in base_feats] +
    [f"se_{f}" for f in base_feats] +
    [f"worst_{f}" for f in base_feats]
)

X_bc = bc_df.iloc[:, 2:].copy()
X_bc.columns = feature_names

y_bc = bc_df.iloc[:, 1].map({"M": 1, "B": -1}).astype(int)
y_bc.name = "diagnosis"

os.makedirs("./data/breast-cancer", exist_ok=True)
X_bc.to_csv("./data/breast-cancer/X.csv", index=False)
y_bc.to_csv("./data/breast-cancer/y.csv", index=False)

## wine quality

In [23]:
import pandas as pd
import os

wine_path = "./data/wine_quality.csv"
wine_df = pd.read_csv(wine_path, sep=";")

X_wine = wine_df.iloc[:, :-1].copy()
X_wine.columns = [
    "fixed_acidity", "volatile_acidity", "citric_acid", "residual_sugar",
    "chlorides", "free_sulfur_dioxide", "total_sulfur_dioxide", "density",
    "pH", "sulphates", "alcohol"
]
y_wine = wine_df.iloc[:, -1].apply(lambda v: 1 if v > 5 else -1)
y_wine.name = "quality"

os.makedirs("./data/wine-quality", exist_ok=True)
X_wine.to_csv("./data/wine-quality/X.csv", index=False)
y_wine.to_csv("./data/wine-quality/y.csv", index=False)

In [24]:
y_wine.value_counts()

quality
 1    855
-1    744
Name: count, dtype: int64

## avila bible

In [ ]:
import pandas as pd
import os

avila_tr_path = "./data/avila-tr.txt"
avila_ts_path = "./data/avila-ts.txt"

feature_cols = [f"F{i}" for i in range(1, 11)]
all_cols = feature_cols + ["class"]

df_tr = pd.read_csv(avila_tr_path, header=None, names=all_cols)
df_ts = pd.read_csv(avila_ts_path, header=None, names=all_cols)

# ignore train and test sets and merge them
avila_df = pd.concat([df_tr, df_ts], ignore_index=True)

X_avila = avila_df[feature_cols].copy()

y_avila = avila_df["class"].apply(lambda c: 1 if c == "A" else -1).astype(int)
y_avila.name = "class"

os.makedirs("./data/avila", exist_ok=True)
X_avila.to_csv("./data/avila/X.csv", index=False)
y_avila.to_csv("./data/avila/y.csv", index=False)

## magic telescope

In [27]:
import pandas as pd
import os

# local loading

magic_path = "./data/magic04.data"

feature_cols = [
    "fLength", "fWidth", "fSize", "fConc", "fConc1",
    "fAsym", "fM3Long", "fM3Trans", "fAlpha", "fDist"
]
all_cols = feature_cols + ["class"]

magic_df = pd.read_csv(magic_path, header=None, names=all_cols)

X_magic = magic_df[feature_cols].copy()
y_magic = magic_df["class"].map({"g": 1, "h": -1}).astype(int)
y_magic.name = "class"

os.makedirs("./data/magic", exist_ok=True)
X_magic.to_csv("./data/magic/X.csv", index=False)
y_magic.to_csv("./data/magic/y.csv", index=False)

## swarm behavious

In [28]:
flocking_path = "./data/Flocking.csv"
flocking_df = pd.read_csv(flocking_path)

flocking_df.columns = flocking_df.columns.str.strip()

target_col = flocking_df.columns[-1]

X_flocking = flocking_df.iloc[:, :-1].copy()
y_raw = flocking_df[target_col]

if set(pd.unique(y_raw)).issubset({0, 1}):
    y_flocking = y_raw.map({0: -1, 1: 1}).astype(int)

elif set(pd.unique(y_raw)).issubset({-1, 1}):
    y_flocking = y_raw.astype(int)
else:

    positive_class = y_raw.value_counts().idxmax()
    y_flocking = y_raw.apply(lambda v: 1 if v == positive_class else -1).astype(int)

y_flocking.name = "class"

os.makedirs("./data/flocking", exist_ok=True)
X_flocking.to_csv("./data/flocking/X.csv", index=False)
y_flocking.to_csv("./data/flocking/y.csv", index=False)

/var/folders/3z/lljdpnns22b_zsxsy4kc5khc0000gn/T/ipykernel_933/4137105710.py:2: DtypeWarning: Columns (0: x1) have mixed types. Specify dtype option on import or set low_memory=False.
  flocking_df = pd.read_csv(flocking_path)